# Generated by Django 5.1.4 on 2026-05-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
    ]
