# Generated by Django 5.1.4 on 2026-05-09 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbox',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chatbox', '-created_at'], name='chat_messag_chatbox_130b09_idx'),
        ),
    ]
