# Generated by Django 5.1.4 on 2026-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbox',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
